### ISSUE TITLE
Presentation [UW]: Demystifying Black-box Models with Symbolic Metamodels

### ISSUE THREAD

**Issue by Ninoko** [pbiecek/InterpretableMachineLearning2020#138]
Team members: Miłosz Michta
Paper: https://papers.nips.cc/paper/9308-demystifying-black-box-models-with-symbolic-metamodels.pdf
Repository: https://github.com/ahmedmalaa/Symbolic-Metamodeling

**Comment by pbiecek** [comment]
Bardzo dobra prezentacja, proszę link umieścić na slacku
