### ISSUE TITLE
Presentation [PW] "AllenNLP Interpret: A Framework for Explaining Predictions of NLP Models"

### ISSUE THREAD

**Issue by k-koprowska** [pbiecek/InterpretableMachineLearning2020#154]
Katarzyna Koprowska, Katarzyna Lorenc
na podstawie artykułu: https://arxiv.org/pdf/1909.09251.pdf
preferowany termin: 28.05.2020
@pbiecek czy ten temat jest akceptowalny?

**Comment by pbiecek** [comment]
Temat jest ciekawy. Proszę zrobić krótkie wprowadzenie do NLP dla osób które nie wiedzą o co chodzi w tych modelach

**Comment by pbiecek** [comment]
4/5
